services:
  goals-auth:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 3001:3001
      - 3002:3002
    env_file:
      - .env
    restart: unless-stopped

  mongo:
    image: mongo:latest
    environment:
      MONGODB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - 27017:27017
    env_file:
      - .env
    restart: unless-stopped
